language: node_js
node_js:
- '0.10'
before_install:
- gem update --system
- gem install compass --pre
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  hipchat:
    rooms:
      secure: BA2A/ACT6YQZ4b2uXnXNNm5eG37KyDg3iisctAtRUOukvANSZF650JKM9KVDl8vyfqYJSl9e/j+VV5bs++ymZZCv6py3pf6eh3R+O8HaE9qQDTz8fcmPl2zRVXPqQ67Mx1TJkNuzRfncX2/naRRM3KVT3Dtk1FhwUn18/hCe1fU=
